# Generated by Django 2.2.24 on 2021-12-28 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0015_auto_20211221_1504'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bus_M_', '0002_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('bus_id', models.AutoField(primary_key=True, serialize=False)),
                ('availability', models.BooleanField(default=True)),
                ('capacity', models.IntegerField()),
                ('driver_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bus_M_.Driver')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('wallet_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('balance', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='request',
            name='departure_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='number_seats',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='user_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.TimeField()),
                ('start', models.CharField(max_length=300)),
                ('destination', models.CharField(max_length=300)),
                ('available_seats', models.IntegerField()),
                ('day', models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thrusday', 'Thrusday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=200)),
                ('running_status', models.BooleanField(default=True)),
                ('bus_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bus_M_.Bus')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField(null=True)),
                ('seat_no', models.IntegerField()),
                ('refund_status', models.BooleanField(default=False)),
                ('schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_M_.Schedule')),
                ('user_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('admin_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
